[tool.poetry]
name = "aoc 2022"
version = "0.1.0"
description = ""
authors = ["Me <someone@somewhe.re>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
